package io.legado.app.help.book.highlight

/** A declaration list, not a stylesheet: imported rules cannot add selectors or scripts. */
object HighlightStyle {
    data class Palette(
        val text: String = "#333333",
        val accent: String = "#008577",
        val background: String = "#ffffff",
        val night: Boolean = false
    )

    private val allowed = setOf(
        "color", "background-color", "background-position", "background-size", "background-repeat",
        "font-size", "font-weight", "font-style", "font-family", "line-height", "letter-spacing",
        "text-align", "text-indent", "text-decoration", "text-decoration-line", "text-decoration-style",
        "text-decoration-color", "text-decoration-thickness", "text-underline-offset", "text-shadow",
        "border", "border-top", "border-bottom", "border-left", "border-right", "border-color",
        "border-width", "border-style", "border-radius", "padding", "padding-top", "padding-bottom",
        "padding-left", "padding-right", "margin", "margin-top", "margin-bottom", "margin-left",
        "margin-right", "display", "vertical-align", "box-shadow"
    )
    private val unsafe = Regex("[<>{}@\\\\]|/\\*|\\*/|url\\s*\\(|expression\\s*\\(|javascript:",
        RegexOption.IGNORE_CASE)

    fun color(name: String, palette: Palette): String {
        if (name == "accent") return palette.accent
        val colors = if (palette.night) mapOf(
            "red" to "#f87171", "orange" to "#fb923c", "yellow" to "#facc15",
            "green" to "#4ade80", "teal" to "#2dd4bf", "blue" to "#60a5fa",
            "purple" to "#c084fc", "pink" to "#f472b6", "brown" to "#bcaaa4",
            "gray" to "#9ca3af"
        ) else mapOf(
            "red" to "#dc2626", "orange" to "#c65d10", "yellow" to "#927000",
            "green" to "#15803d", "teal" to "#0f766e", "blue" to "#2563eb",
            "purple" to "#9333ea", "pink" to "#db2777", "brown" to "#795548",
            "gray" to "#6b7280"
        )
        return colors[name] ?: palette.accent
    }

    fun declarations(rule: HighlightRule, palette: Palette, assetUrl: (String) -> String): Map<String, String> {
        val values = linkedMapOf<String, String>()
        val raw = rule.styleCssText.split(';').mapNotNull { entry ->
            val split = entry.indexOf(':')
            if (split < 1) null else entry.substring(0, split).trim().lowercase() to
                entry.substring(split + 1).trim()
        }.toMap()
        if (raw.isEmpty() || raw.keys.all { it == "font-family" }) {
            val color = color(rule.styleColorType, palette)
            when (rule.styleType) {
                "background" -> {
                    values["background-color"] = color
                    values["color"] = "#ffffff"
                }
                "textColor" -> values["color"] = color
                else -> {
                    values["text-decoration-line"] = if (rule.styleType == "strikethrough") "line-through" else "underline"
                    values["text-decoration-style"] = when (rule.styleType) {
                        "doubleLine" -> "double"
                        "dottedLine" -> "dotted"
                        "wavyLine" -> "wavy"
                        else -> "solid"
                    }
                    values["text-decoration-color"] = color
                }
            }
        }
        raw.forEach { (property, original) ->
            if (property !in allowed) return@forEach
            var value = original
                .replace("{primaryColor}", palette.text)
                .replace("{textColor}", palette.text)
                .replace("{accentColor}", palette.accent)
                .replace("{backgroundColor}", palette.background)
                .removeSuffix("!important").trim()
            if (property == "font-family" && value.contains("reeden-font:", true)) value = "inherit"
            if (value.isEmpty() || value == "px" || value.length > 1024 || unsafe.containsMatchIn(value)) return@forEach
            // A hidden or out-of-flow match would remove words from selection/pagination.
            if (property == "display" && value !in setOf("inline", "inline-block", "block")) return@forEach
            values[property] = value
        }
        rule.asset?.let { id ->
            val url = assetUrl(id)
            // Asset URLs are generated by the reader, never taken from the package CSS.
            if (!url.contains('"') && !url.contains('<') && !url.contains('>')) {
                values["background-image"] = "url(\"" + url + "\")"
                values.putIfAbsent("background-size", "100% 100%")
                values.putIfAbsent("background-repeat", "no-repeat")
                values.putIfAbsent("background-position", "center")
                nineSlice(rule, raw)?.let { slices ->
                    values["border-image-source"] = "url(\"" + url + "\")"
                    values["border-image-slice"] = slices + " fill"
                    // These are source-image caps, not text padding. Let the
                    // browser fit their intrinsic dimensions with one scale for
                    // all four sides; assigning the padding independently would
                    // squash a half-image cap into a few pixels and lose its art.
                    values["border-image-width"] = "auto"
                    values["border-image-repeat"] = "stretch"
                    values["background-image"] = "none"
                }
            }
        }
        values["box-decoration-break"] = "clone"
        values["-webkit-box-decoration-break"] = "clone"
        return values
    }

    /** Reeden stores the stretch rectangle as x1,y1,x2,y2, optionally / imageWidth,imageHeight. */
    private fun nineSlice(rule: HighlightRule, raw: Map<String, String>): String? {
        val spec = raw["reeden-background-nine-slice"] ?: raw["--reeden-background-nine-slice"] ?: return null
        val numbers = Regex("[0-9]+(?:\\.[0-9]+)?").findAll(spec).map { it.value.toDouble() }.toList()
        if (numbers.size != 4 && numbers.size != 6) return null
        val width = numbers.getOrNull(4) ?: rule.imageWidth.toDouble()
        val height = numbers.getOrNull(5) ?: rule.imageHeight.toDouble()
        val (x1, y1, x2, y2) = numbers
        if (width <= 0 || height <= 0 || x1 >= x2 || y1 >= y2 || x2 > width || y2 > height) return null
        return listOf(y1 / height, (width - x2) / width, (height - y2) / height, x1 / width)
            .joinToString(" ") { java.lang.String.format(java.util.Locale.ROOT, "%.4f%%", it * 100) }
    }

    fun css(rule: HighlightRule, palette: Palette, assetUrl: (String) -> String): String {
        val values = declarations(rule, palette, assetUrl).toMutableMap()
        val layout = inlineLayout(rule, palette)?.takeIf {
            values.containsKey("background-image") || values.containsKey("border-image-source")
        }
        if (layout != null) {
            // Cloned inline padding disables Chromium's text justification. Paint
            // the same complete image outside the glyph box, while a separate,
            // sliceable inline wrapper owns the space at the two match boundaries.
            values.keys.filter { it == "padding" || it.startsWith("padding-") ||
                it == "margin" || it.startsWith("margin-") }.toList().forEach(values::remove)
            values["padding"] = "0"
            values["margin"] = "0"
            if (!values.containsKey("border-image-source")) {
                values["border-image-source"] = values.getValue("background-image")
                // Protect a narrow outer cap when the package does not provide
                // a stretch rectangle. Stretching the entire image scales its
                // transparent margins with each line's width, making short last
                // lines protrude. Keep all source pixels, including soft shadows.
                val caps = inlineImageCaps(rule)
                values["border-image-slice"] = caps ?: "0 fill"
                values["border-image-width"] = if (caps == null) "0" else "auto"
            }
            values["border-image-outset"] = layout.outset
            values["background-image"] = "none"
        }
        return values.entries.joinToString(";") { it.key + ":" + it.value + "!important" } +
            layout?.let { ";line-height:${it.fallbackLineHeight}!important;line-height:var(--legado-highlight-line-grid,${it.lineHeight})!important" }.orEmpty()
    }

    private fun inlineImageCaps(rule: HighlightRule): String? {
        val width = rule.imageWidth.toDouble()
        val height = rule.imageHeight.toDouble()
        if (width <= 2 || height <= 2) return null
        // At most half an image-height per cap leaves room for even a one-glyph
        // final line. The wide middle retains the package's horizontal stretch.
        val horizontal = minOf(width / 8, height / 2) / width
        val vertical = (height - 1) / 2 / height
        return listOf(vertical, horizontal, vertical, horizontal).joinToString(" ") {
            java.lang.String.format(java.util.Locale.ROOT, "%.6f%%", it * 100)
        } + " fill"
    }

    data class InlineLayout(val inset: String, val outset: String, val spaceLeft: String, val spaceRight: String,
                            val lineHeight: String, val fallbackLineHeight: String)

    /** Inline padding paints outside the line box, and Chromium does not reserve its cloned end. */
    fun inlineLayout(rule: HighlightRule, palette: Palette): InlineLayout? {
        if (rule.asset == null) return null
        val values = declarations(rule, palette) { "" }
        if (values["display"] != "inline" || values["background-size"] != "100% 100%" ||
            values["background-repeat"] != "no-repeat" || values["background-position"] != "center") return null
        // A real CSS border or colored background needs its original box painting.
        if (values.keys.any { it == "border" || it in setOf("border-top", "border-right", "border-bottom", "border-left", "border-width") } ||
            values["background-color"]?.let { it != "transparent" } == true) return null
        val sides = listOf("top", "right", "bottom", "left")
        // Percent padding depends on the containing block, not the font. Leave such
        // publisher-specific declarations alone instead of guessing their geometry.
        val length = Regex("(?:0|(?:[0-9]+(?:\\.[0-9]+)?|\\.[0-9]+)(?:px|em|rem))")
        fun box(name: String): List<String>? {
            val result = MutableList(4) { "0px" }
            values.forEach { (property, value) ->
                if (property == name) {
                    val parts = value.trim().split(Regex("\\s+"))
                    if (parts.size !in 1..4) return null
                    result[0] = parts[0]
                    result[1] = parts.getOrElse(1) { parts[0] }
                    result[2] = parts.getOrElse(2) { parts[0] }
                    result[3] = parts.getOrElse(3) { result[1] }
                } else {
                    val side = sides.indexOf(property.removePrefix("$name-"))
                    if (property.startsWith("$name-") && side >= 0) result[side] = value
                }
            }
            if (result.any { !length.matches(it) }) return null
            return result.map { if (it == "0") "0px" else it }
        }
        val normalized = box("padding") ?: return null
        val margins = box("margin") ?: return null
        val vertical = "max(${normalized[0]},${normalized[2]})"
        fun inFlowFont(value: String): String {
            if (!value.endsWith("em") || value.endsWith("rem")) return value
            val size = values["font-size"] ?: return value
            val relativeSize = if (size.endsWith('%')) {
                size.dropLast(1).toDoubleOrNull()?.let { "${it / 100}em" }
            } else size.takeIf(length::matches)
            return relativeSize?.let { "calc(${value.removeSuffix("em")} * $it)" } ?: value
        }
        val horizontal = "max(${inFlowFont(normalized[1])},${inFlowFont(normalized[3])})"
        val requested = values["line-height"]
        val base = when {
            requested == null || requested in setOf("normal", "inherit") -> "1lh"
            Regex("[0-9]+(?:\\.[0-9]+)?").matches(requested) -> "${requested}em"
            length.matches(requested) -> requested
            else -> return null
        }
        // A rule may enlarge the font while inheriting a smaller paragraph line
        // height. Keep room for its glyph metrics before adding the artwork edges.
        return InlineLayout(horizontal, normalized.joinToString(" "),
            "calc(${inFlowFont(normalized[3])} + ${inFlowFont(margins[3])})",
            "calc(${inFlowFont(normalized[1])} + ${inFlowFont(margins[1])})",
            "calc(max($base,1.5em) + $vertical + $vertical)",
            "calc(max(${if (base == "1lh") "1.5em" else base},1.5em) + $vertical + $vertical)")
    }
}
