package io.legado.app.utils

/** Fixed UI copy only. Keys and editable user/source values are never rewritten. */
internal val auditedUiLabels = mapOf(
    "导出 JSON" to "Xuất JSON",
    "查询书架书籍" to "Tra cứu sách trong tủ",
    "读取书籍详情" to "Đọc thông tin sách",
    "管理书架分组" to "Quản lý nhóm tủ sách",
    "管理书架标签" to "Quản lý nhãn tủ sách",
    "设置书籍分组" to "Đặt nhóm cho sách",
    "设置书籍标签" to "Đặt nhãn cho sách",
    "查询阅读记录" to "Tra cứu lịch sử đọc",
    "读取章节目录" to "Đọc mục lục",
    "搜索章节正文" to "Tìm nội dung chương",
    "读取章节正文" to "Đọc nội dung chương",
    "列出书源" to "Liệt kê nguồn sách",
    "搜索书源内容" to "Tìm nội dung từ nguồn sách",
    "创建书源" to "Tạo nguồn sách",
    "读取书源详情" to "Đọc thông tin nguồn sách",
    "更新书源" to "Cập nhật nguồn sách",
    "抓取网页源码" to "Lấy mã nguồn trang web",
    "调试书源规则" to "Kiểm tra quy tắc nguồn sách",
    "阅读网络请求" to "Yêu cầu mạng của trình đọc",
    "阅读 WebView" to "WebView của trình đọc",
    "抓包网络请求" to "Ghi nhận yêu cầu mạng",
    "联网搜索" to "Tìm kiếm trên web",
    "生成图片" to "Tạo ảnh",
    "读取角色资料" to "Đọc hồ sơ nhân vật",
    "新增或更新角色" to "Thêm hoặc cập nhật nhân vật",
    "读取角色关系网" to "Đọc quan hệ nhân vật",
    "新增或更新角色关系" to "Thêm hoặc cập nhật quan hệ nhân vật",
    "删除角色关系" to "Xóa quan hệ nhân vật",
    "读取 AI 图片库" to "Đọc thư viện ảnh AI",
    "设置角色图库头像" to "Đặt ảnh đại diện nhân vật từ thư viện",
    "生成角色头像" to "Tạo ảnh đại diện nhân vật",
    "读取配音目录" to "Đọc danh mục giọng đọc",
    "设置角色配音" to "Đặt giọng đọc cho nhân vật",
    "批量分配角色配音" to "Phân giọng cho nhiều nhân vật",
    "清空角色配音" to "Xóa phân giọng nhân vật",
    "读取发言人分组" to "Đọc nhóm giọng đọc",
    "新增或更新发言人分组" to "Thêm hoặc cập nhật nhóm giọng đọc",
    "删除发言人分组" to "Xóa nhóm giọng đọc",
    "读取朗读配乐曲库" to "Đọc thư viện nhạc nền nghe sách",
    "分配朗读配乐范围" to "Đặt phạm vi nhạc nền nghe sách",
    "读取世界书" to "Đọc sách thế giới",
    "新增或更新世界书" to "Thêm hoặc cập nhật sách thế giới",
    "删除世界书" to "Xóa sách thế giới",
    "新增或更新世界书条目" to "Thêm hoặc cập nhật mục sách thế giới",
    "删除世界书条目" to "Xóa mục sách thế giới",
    "读取世界书启用" to "Đọc liên kết sách thế giới",
    "启用世界书" to "Bật sách thế giới",
    "移除世界书启用" to "Gỡ liên kết sách thế giới",
    "导入世界书 JSON" to "Nhập JSON sách thế giới",
    "导出世界书 JSON" to "Xuất JSON sách thế giới",
    "读取应用设置" to "Đọc cài đặt ứng dụng",
    "修改应用设置" to "Thay đổi cài đặt ứng dụng",
    "批量修改设置" to "Thay đổi nhiều cài đặt",
    "工作区：列出文件" to "Không gian làm việc: liệt kê tệp",
    "工作区：读取文件" to "Không gian làm việc: đọc tệp",
    "工作区：按行读取" to "Không gian làm việc: đọc theo dòng",
    "工作区：正则读取" to "Không gian làm việc: đọc bằng biểu thức chính quy",
    "工作区：正则搜索" to "Không gian làm việc: tìm bằng biểu thức chính quy",
    "工作区：保存输入为文件" to "Không gian làm việc: lưu nội dung vào tệp",
    "工作区：写入文件" to "Không gian làm việc: ghi tệp",
    "工作区：编辑文件" to "Không gian làm việc: sửa tệp",
    "工作区：精确替换" to "Không gian làm việc: thay thế chính xác",
    "工作区：正则替换" to "Không gian làm việc: thay thế bằng biểu thức chính quy",
    "工作区：行号编辑" to "Không gian làm việc: sửa theo số dòng",
    "工作区：插入文本" to "Không gian làm việc: chèn văn bản",
    "工作区：查看差异" to "Không gian làm việc: xem thay đổi",
    "书架" to "Tủ sách",
    "AI workspace" to "Không gian làm việc AI",
    "书源" to "Nguồn sách",
    "阅读" to "Đọc sách",
    "阅读网络" to "Mạng của trình đọc",
    "AI 生图" to "Tạo ảnh AI",
    "MCP 工具" to "Công cụ MCP",
    "世界书已导入" to "Đã nhập sách thế giới",
    "世界书 JSON 解析失败" to "Không thể đọc JSON sách thế giới",
    "工作区：删除文件" to "Không gian làm việc: xóa tệp",
    "工作区：列出备份" to "Không gian làm việc: liệt kê bản sao lưu",
    "工作区：创建备份" to "Không gian làm việc: tạo bản sao lưu",
    "工作区：恢复备份" to "Không gian làm việc: khôi phục bản sao lưu",
    "工作区：导入书源" to "Không gian làm việc: nhập nguồn sách",
    "工作区：创建书源文件" to "Không gian làm việc: tạo tệp nguồn sách",
    "工作区：调试书源" to "Không gian làm việc: kiểm tra nguồn sách",
    "工作区：应用书源" to "Không gian làm việc: áp dụng nguồn sách",

    "%s 个全局启用 · %s 条条目" to "Bật toàn cục: %s · %s mục",
    "%s 条目" to "%s mục",
    "%s 个绑定" to "%s liên kết",
    "最多 %s 条" to "Tối đa %s mục",
    "扫 %s" to "Quét %s",
    "已记录 %s 个角色" to "Đã lưu %s nhân vật",
    "主角视角 · %s 个角色 · %s 条关系" to "Góc nhìn nhân vật chính · %s nhân vật · %s quan hệ",
    "%s 个失效发言人 · 不参与自动分配" to "%s giọng không khả dụng · Không tự động phân vai",
    "%s 个发言人 · %s" to "%s giọng đọc · %s",
    "已选 %s" to "Đã chọn %s",
    "%s发言人" to "%s giọng đọc",
    "%s情绪" to "%s cảm xúc",
    "段落 %s" to "Đoạn %s",
    "已启用" to "Đã bật",
    "已停用" to "Đã tắt",
    "已失效" to "Không khả dụng",
    "文件夹名不能为空" to "Tên thư mục không được để trống",

    "发言人格式示例：" to "Ví dụ định dạng giọng đọc:",
    "分组格式示例：" to "Ví dụ định dạng nhóm:",
    "情绪字段：" to "Trường cảm xúc:",
    "返回" to "Quay lại",
    "刷新" to "Làm mới",
    "新增" to "Thêm mới",
    "新增世界书" to "Thêm sách thế giới",
    "编辑世界书" to "Sửa sách thế giới",
    "世界书" to "Sách thế giới",
    "本地导入" to "Nhập từ thiết bị",
    "网络导入" to "Nhập từ mạng",
    "在线导入" to "Nhập trực tuyến",
    "粘贴导入" to "Nhập từ nội dung đã sao chép",
    "搜索世界书、条目、关键词" to "Tìm sách thế giới, mục hoặc từ khóa",
    "无描述" to "Chưa có mô tả",
    "全局启用" to "Bật toàn cục",
    "可角色绑定" to "Có thể gắn với nhân vật",
    "资料库停用" to "Thư viện đã tắt",
    "编辑" to "Sửa",
    "复制" to "Sao chép",
    "导出" to "Xuất",
    "新增条目" to "Thêm mục",
    "编辑条目" to "Sửa mục",
    "删除" to "Xóa",
    "暂无条目" to "Chưa có mục nào",
    "常驻" to "Luôn áp dụng",
    "正则" to "Biểu thức chính quy",
    "粘贴 RikkaHub lorebook JSON" to "Dán JSON lorebook RikkaHub",
    "标准 lorebook JSON" to "JSON lorebook chuẩn",
    "资料库设置" to "Cài đặt thư viện",
    "资料库可用" to "Bật thư viện",
    "名称" to "Tên",
    "描述" to "Mô tả",
    "每本世界书最大命中条数" to "Số mục khớp tối đa cho mỗi sách thế giới",
    "系统提示词之后" to "Sau lời nhắc hệ thống",
    "适合长期设定和角色资料" to "Phù hợp với thiết lập lâu dài và hồ sơ nhân vật",
    "对话正文之前" to "Trước nội dung hội thoại",
    "适合本轮前置补充信息" to "Bổ sung thông tin trước lượt hội thoại này",
    "最后一条用户消息之前" to "Trước tin nhắn cuối của người dùng",
    "适合贴近当前问题的补充" to "Bổ sung thông tin liên quan câu hỏi hiện tại",
    "按深度插入" to "Chèn theo độ sâu",
    "按下方插入深度放入历史消息附近" to "Chèn vào lịch sử theo độ sâu bên dưới",
    "系统消息" to "Tin nhắn hệ thống",
    "最高优先级设定" to "Thiết lập ưu tiên cao nhất",
    "用户消息" to "Tin nhắn người dùng",
    "模拟用户侧补充" to "Mô phỏng thông tin bổ sung từ người dùng",
    "助手消息" to "Tin nhắn trợ lý",
    "模拟助手侧记忆" to "Mô phỏng bộ nhớ của trợ lý",
    "关键词命中后注入内容" to "Chèn nội dung khi khớp từ khóa",
    "启用条目" to "Bật mục",
    "常驻注入" to "Luôn chèn nội dung",
    "关键词按正则匹配" to "Khớp từ khóa bằng biểu thức chính quy",
    "区分大小写" to "Phân biệt chữ hoa và chữ thường",
    "条目名称" to "Tên mục",
    "内容" to "Nội dung",
    "关键词，逗号或换行分隔" to "Từ khóa, phân cách bằng dấu phẩy hoặc xuống dòng",
    "二级关键词" to "Từ khóa phụ",
    "排除关键词" to "Từ khóa loại trừ",
    "插入位置" to "Vị trí chèn",
    "消息角色" to "Vai trò tin nhắn",
    "优先级" to "Mức ưu tiên",
    "插入深度" to "Độ sâu chèn",
    "扫描深度" to "Độ sâu quét",
    "最大命中数" to "Số lần khớp tối đa",
    "正则表达式有错误，不能保存。" to "Biểu thức chính quy không hợp lệ, không thể lưu.",
    "取消" to "Hủy",
    "保存" to "Lưu",
    "角色资料" to "Hồ sơ nhân vật",
    "关系网" to "Quan hệ nhân vật",
    "还没有角色，先添加主角或重要角色。" to "Chưa có nhân vật. Hãy thêm nhân vật chính hoặc nhân vật quan trọng.",
    "这个分类还没有角色。" to "Nhóm này chưa có nhân vật.",
    "主角" to "Nhân vật chính",
    "重要角色" to "Nhân vật quan trọng",
    "普通角色" to "Nhân vật thường",
    "本书角色库" to "Nhân vật trong sách",
    "角色卡会只绑定当前书籍" to "Hồ sơ nhân vật chỉ gắn với sách hiện tại",
    "添加" to "Thêm",
    "更多" to "Thêm tùy chọn",
    "编辑角色" to "Sửa nhân vật",
    "修改头像、身份、技能和生平" to "Sửa ảnh đại diện, thân phận, kỹ năng và tiểu sử",
    "删除角色" to "Xóa nhân vật",
    "同时删除与此角色相关的关系" to "Đồng thời xóa các quan hệ của nhân vật này",
    "关闭" to "Đóng",
    "角色卡片" to "Hồ sơ nhân vật",
    "角色不存在" to "Nhân vật không tồn tại",
    "身份" to "Thân phận",
    "技能" to "Kỹ năng",
    "属性" to "Thuộc tính",
    "形象描述" to "Ngoại hình",
    "性格描述" to "Tính cách",
    "角色生平" to "Tiểu sử nhân vật",
    "角色配音" to "Giọng nhân vật",
    "使用默认朗读引擎" to "Dùng bộ đọc mặc định",
    "切换" to "Đổi",
    "未填写" to "Chưa điền",
    "角色头像" to "Ảnh đại diện nhân vật",
    "本地" to "Trên thiết bị",
    "在线" to "Trực tuyến",
    "图库" to "Thư viện ảnh",
    "生成" to "Tạo",
    "清除" to "Xóa",
    "角色名称" to "Tên nhân vật",
    "角色年纪" to "Tuổi nhân vật",
    "角色身份" to "Thân phận nhân vật",
    "角色技能" to "Kỹ năng nhân vật",
    "角色属性" to "Thuộc tính nhân vật",
    "角色形象描述" to "Ngoại hình nhân vật",
    "角色性格描述" to "Tính cách nhân vật",
    "使用书籍或全局默认朗读引擎" to "Dùng bộ đọc mặc định của sách hoặc toàn cục",
    "暂无可用朗读引擎。" to "Chưa có bộ đọc khả dụng.",
    "选择发言人" to "Chọn giọng đọc",
    "使用默认" to "Dùng mặc định",
    "角色性别" to "Giới tính nhân vật",
    "未知" to "Chưa rõ",
    "男" to "Nam",
    "女" to "Nữ",
    "角色类型" to "Loại nhân vật",
    "角色关系网" to "Mạng quan hệ nhân vật",
    "添加关系" to "Thêm quan hệ",
    "编辑关系" to "Sửa quan hệ",
    "暂无关系，点击右上角添加角色关系。" to "Chưa có quan hệ. Nhấn góc trên bên phải để thêm.",
    "关系列表" to "Danh sách quan hệ",
    "收起" to "Thu gọn",
    "展开" to "Mở rộng",
    "暂无关系，点击右上角添加" to "Chưa có quan hệ. Nhấn góc trên bên phải để thêm",
    "角色 A" to "Nhân vật A",
    "角色 B" to "Nhân vật B",
    "关系名称" to "Tên quan hệ",
    "关系属性" to "Thuộc tính quan hệ",
    "关系说明" to "Mô tả quan hệ",
    "选择角色 A" to "Chọn nhân vật A",
    "选择角色 B" to "Chọn nhân vật B",
    "请选择角色" to "Chọn nhân vật",
    "更换" to "Thay đổi",
    "已选" to "Đã chọn",
    "发言人管理" to "Quản lý giọng đọc",
    "多角色自动分配会优先使用这里启用的发言人" to "Tự động phân vai sẽ ưu tiên các giọng đọc được bật tại đây",
    "新建分组" to "Thêm nhóm",
    "编辑分组" to "Sửa nhóm",
    "暂无发言人分组" to "Chưa có nhóm giọng đọc",
    "没有被标记失效的发言人" to "Không có giọng đọc bị đánh dấu không khả dụng",
    "这个分组还没有发言人" to "Nhóm này chưa có giọng đọc",
    "添加发言人" to "Thêm giọng đọc",
    "重命名" to "Đổi tên",
    "移除" to "Gỡ bỏ",
    "分组名称" to "Tên nhóm",
    "启用分组" to "Bật nhóm",
    "搜索发言人 / 分组 / toneID" to "Tìm giọng đọc / nhóm / toneID",
    "没有匹配的发言人" to "Không tìm thấy giọng đọc phù hợp",
    "已展开" to "Đã mở rộng",
    "已收起" to "Đã thu gọn",
    "取消全选" to "Bỏ chọn tất cả",
    "全选" to "Chọn tất cả",
    "已在组内" to "Đã có trong nhóm",
    "删除分组" to "Xóa nhóm",
    "暂无朗读引擎" to "Chưa có bộ đọc",
    "搜索发言人 / toneID / 情绪" to "Tìm giọng đọc / toneID / cảm xúc",
    "无情绪" to "Không có cảm xúc",
    "登录 / 刷新授权" to "Đăng nhập / Làm mới xác thực",
    "当前" to "Hiện tại",
    "选择" to "Chọn",
    "默认" to "Mặc định",
    "发言人" to "Giọng đọc",
    "朗读引擎" to "Bộ đọc",
    "导入" to "Nhập",
    "导出全部" to "Xuất tất cả",
    "清缓存" to "Xóa bộ nhớ đệm",
    "导入朗读规则" to "Nhập quy tắc đọc",
    "默认规则" to "Quy tắc mặc định",
    "导入内置 HTTP TTS 规则" to "Nhập quy tắc HTTP TTS tích hợp",
    "从本机 txt/json 文件导入" to "Nhập tệp txt/json từ thiết bị",
    "通过 URL 导入朗读规则" to "Nhập quy tắc đọc qua URL",
    "登录" to "Đăng nhập",
    "发言人列表" to "Danh sách giọng đọc",
    "情绪" to "Cảm xúc",
    "选择此引擎后，普通朗读会使用该引擎；角色配音可在角色编辑页按发言人单独指定。" to "Bộ đọc này sẽ dùng cho việc đọc thông thường. Có thể chọn giọng riêng cho từng nhân vật trong trang sửa nhân vật.",
    "当前朗读" to "Đang đọc",
    "搜索角色" to "Tìm nhân vật",
    "没有可选角色" to "Không có nhân vật để chọn",
    "修改片段分配" to "Sửa phân vai đoạn",
    "全屏" to "Toàn màn hình",
    "退出全屏" to "Thoát toàn màn hình",
    "设置" to "Cài đặt",
    "上一章" to "Chương trước",
    "下一章" to "Chương sau",
    "HTTP 朗读规则" to "Quy tắc HTTP TTS",
    "粘贴" to "Dán",
    "登录头" to "Header đăng nhập",
    "清登录头" to "Xóa header đăng nhập",
    "日志" to "Nhật ký",
    "帮助" to "Trợ giúp",
    "发言人列表 JSON" to "JSON danh sách giọng đọc",
    "情绪列表 JSON" to "JSON danh sách cảm xúc",
    "并发率" to "Mức đồng thời",
    "生成线程数" to "Số luồng tạo âm thanh",
    "登录 URL" to "URL đăng nhập",
    "登录 UI" to "Giao diện đăng nhập",
    "登录检测 JS" to "JS kiểm tra đăng nhập",
    "可为空；为空时该 HTTP TTS 会作为普通发言人使用。" to "Có thể để trống. Khi đó HTTP TTS này được dùng như một giọng đọc thông thường.",
    "可为空；填写后角色和快捷选择可选默认情绪。" to "Có thể để trống. Khi điền, có thể chọn cảm xúc mặc định cho nhân vật và trong bộ chọn nhanh.",
    "暂无书籍结果" to "Không có kết quả sách",
    "暂无搜索结果" to "Không có kết quả tìm kiếm",
    "暂无图片结果" to "Không có kết quả ảnh",
    "复制原始数据" to "Sao chép dữ liệu gốc",
    "应用主题" to "Bộ giao diện",
    "日间" to "Ban ngày",
    "夜间" to "Ban đêm",
    "导航样式" to "Kiểu điều hướng",
    "界面主题" to "Chủ đề giao diện",
    "顶栏" to "Thanh trên",
    "底栏" to "Thanh dưới",
    "封面图集" to "Bộ ảnh bìa",
    "使用内置界面主题" to "Dùng chủ đề tích hợp",
    "缺省: 常规顶栏" to "Mặc định: thanh trên thông thường",
    "使用默认 MD3 常规底栏" to "Dùng thanh dưới MD3 mặc định",
    "使用默认封面图集" to "Dùng bộ ảnh bìa mặc định",
    "默认缺省: 常规" to "Mặc định: thông thường",
    "悬浮" to "Nổi",
    "常规" to "Thông thường",
    "侧栏" to "Thanh bên",
    "文件夹名" to "Tên thư mục",
    "正在请求跳转链接/应用，是否跳转？" to "Bạn có muốn mở liên kết hoặc ứng dụng này?",
    "属性：%s" to "Thuộc tính: %s",
    "强度：%s" to "Cường độ: %s",
    "关系强度 %s" to "Cường độ quan hệ: %s",
    "%s 个" to "%s nhân vật",
    "%s 条" to "%s quan hệ",
    "确定删除“%s”？不会删除原始 TTS 引擎。" to "Xóa nhóm “%s”? Bộ đọc TTS gốc sẽ được giữ lại.",
    "添加 %s" to "Thêm %s",
    "还有 %s 个发言人未展开" to "Còn %s giọng đọc chưa hiển thị"
)
