export default {
  base: {
    name: 'Cơ bản',
    children: [
      {
        title: 'Loại nguồn',
        id: 'bookSourceType',
        type: 'Array',
        array: ['Văn bản', 'Âm thanh', 'Hình ảnh', 'Tệp', 'Video'],
        required: true,
      },
      {
        title: 'Tên miền nguồn',
        id: 'bookSourceUrl',
        type: 'String',
        hint: 'Thường là trang chủ, ví dụ: https://www.qidian.com',
        required: true,
      },
      {
        title: 'Tên nguồn',
        id: 'bookSourceName',
        type: 'String',
        hint: 'Hiển thị trong danh sách nguồn',
        required: true,
      },
      {
        title: 'Nhóm nguồn',
        id: 'bookSourceGroup',
        type: 'String',
        hint: 'Mô tả đặc điểm của nguồn',
      },
      {
        title: 'Ghi chú nguồn',
        id: 'bookSourceComment',
        type: 'String',
        hint: 'Mô tả tác giả và trạng thái nguồn',
      },
      {
        title: 'Địa chỉ đăng nhập',
        id: 'loginUrl',
        type: 'String',
        hint: 'Nhập URL đăng nhập, chỉ cần với nguồn yêu cầu đăng nhập',
      },
      {
        title: 'Giao diện đăng nhập',
        id: 'loginUi',
        type: 'String',
        hint: 'Giao diện đăng nhập tùy chỉnh',
      },
      {
        title: 'Kiểm tra đăng nhập',
        id: 'loginCheckJs',
        type: 'String',
        hint: 'JS kiểm tra đăng nhập',
      },
      {
        title: 'Giải mã ảnh bìa',
        id: 'coverDecodeJs',
        type: 'String',
        hint: 'JS giải mã ảnh bìa',
      },
      {
        title: 'Kiểm tra liên kết',
        id: 'bookUrlPattern',
        type: 'String',
        hint: 'Regex URL sách, dùng khi tên miền trang chi tiết khác tên miền nguồn để thêm sách bằng URL',
      },
      {
        title: 'Header yêu cầu',
        id: 'header',
        type: 'String',
        hint: 'Định danh trình khách',
      },
      {
        title: 'Mô tả biến',
        id: 'variableComment',
        type: 'String',
        hint: 'Mô tả biến của nguồn sách',
      },
      {
        title: 'Giới hạn yêu cầu',
        id: 'concurrentRate',
        type: 'String',
        hint: 'Ví dụ: 1000 (cách nhau 1000ms) hoặc 1/1000 (1 yêu cầu trong 1000ms)',
      },
      {
        title: 'Thư viện JS',
        id: 'jsLib',
        type: 'String',
        hint: 'Nhập JS hoặc đối tượng key-value để tải tệp JS trực tuyến',
      },
    ],
  },
  search: {
    name: 'Tìm kiếm',
    children: [
      {
        title: 'Địa chỉ tìm kiếm',
        id: 'searchUrl',
        type: 'String',
        hint: '[có thể bỏ tên miền]/search.php@kw={{key}}',
      },
      {
        title: 'Từ khóa kiểm tra',
        namespace: 'ruleSearch',
        id: 'checkKeyWord',
        type: 'String',
        hint: 'Từ khóa kiểm tra, nên điền',
      },
      {
        title: 'Quy tắc danh sách',
        namespace: 'ruleSearch',
        id: 'bookList',
        type: 'String',
        hint: 'Chọn nút sách (kết quả List<Element>)',
      },
      {
        title: 'Quy tắc tên sách',
        namespace: 'ruleSearch',
        id: 'name',
        type: 'String',
        hint: 'Chọn tên sách trong nút (String)',
      },
      {
        title: 'Quy tắc tác giả',
        namespace: 'ruleSearch',
        id: 'author',
        type: 'String',
        hint: 'Chọn tác giả trong nút (String)',
      },
      {
        title: 'Quy tắc phân loại',
        namespace: 'ruleSearch',
        id: 'kind',
        type: 'String',
        hint: 'Chọn phân loại trong nút (String)',
      },
      {
        title: 'Quy tắc số chữ',
        namespace: 'ruleSearch',
        id: 'wordCount',
        type: 'String',
        hint: 'Chọn số chữ trong nút (String)',
      },
      {
        title: 'Chương mới nhất',
        namespace: 'ruleSearch',
        id: 'lastChapter',
        type: 'String',
        hint: 'Chọn chương mới nhất trong nút (String)',
      },
      {
        title: 'Quy tắc giới thiệu',
        namespace: 'ruleSearch',
        id: 'intro',
        type: 'String',
        hint: 'Chọn giới thiệu sách trong nút (String)',
      },
      {
        title: 'Quy tắc ảnh bìa',
        namespace: 'ruleSearch',
        id: 'coverUrl',
        type: 'String',
        hint: 'Chọn ảnh bìa trong nút (URL String)',
      },
      {
        title: 'Địa chỉ chi tiết',
        namespace: 'ruleSearch',
        id: 'bookUrl',
        type: 'String',
        hint: 'Chọn URL trang chi tiết sách (URL String)',
      },
    ],
  },
  find: {
    name: 'Khám phá',
    children: [
      {
        title: 'Địa chỉ khám phá',
        id: 'exploreUrl',
        type: 'String',
        hint: 'Định dạng mục khám phá: <name>::<url> hoặc {url:<url>,title:<name>,style:...}. Dạng đầu phân cách bằng xuống dòng hoặc &&; dạng sau đặt trong mảng. Có thể tạo bằng JS.',
      },
      {
        title: 'Quy tắc danh sách',
        namespace: 'ruleExplore',
        id: 'bookList',
        type: 'String',
        hint: 'Chọn nút sách (kết quả List<Element>)',
      },
      {
        title: 'Quy tắc tên sách',
        namespace: 'ruleExplore',
        id: 'name',
        type: 'String',
        hint: 'Chọn tên sách trong nút (String)',
      },
      {
        title: 'Quy tắc tác giả',
        namespace: 'ruleExplore',
        id: 'author',
        type: 'String',
        hint: 'Chọn tác giả trong nút (String)',
      },
      {
        title: 'Quy tắc phân loại',
        namespace: 'ruleExplore',
        id: 'kind',
        type: 'String',
        hint: 'Chọn phân loại trong nút (String)',
      },
      {
        title: 'Quy tắc số chữ',
        namespace: 'ruleExplore',
        id: 'wordCount',
        type: 'String',
        hint: 'Chọn số chữ trong nút (String)',
      },
      {
        title: 'Chương mới nhất',
        namespace: 'ruleExplore',
        id: 'lastChapter',
        type: 'String',
        hint: 'Chọn chương mới nhất trong nút (String)',
      },
      {
        title: 'Quy tắc giới thiệu',
        namespace: 'ruleExplore',
        id: 'intro',
        type: 'String',
        hint: 'Chọn giới thiệu sách trong nút (String)',
      },
      {
        title: 'Quy tắc ảnh bìa',
        namespace: 'ruleExplore',
        id: 'coverUrl',
        type: 'String',
        hint: 'Chọn ảnh bìa trong nút (URL String)',
      },
      {
        title: 'Địa chỉ chi tiết',
        namespace: 'ruleExplore',
        id: 'bookUrl',
        type: 'String',
        hint: 'Chọn URL trang chi tiết sách (URL String)',
      },
    ],
  },
  detail: {
    name: 'Chi tiết',
    children: [
      {
        title: 'Xử lý trước',
        namespace: 'ruleBookInfo',
        id: 'init',
        type: 'String',
        hint: 'Tăng tốc lấy thông tin chi tiết, chỉ hỗ trợ quy tắc AllInOne',
      },
      {
        title: 'Quy tắc tên sách',
        namespace: 'ruleBookInfo',
        id: 'name',
        type: 'String',
        hint: 'Chọn tên sách trong nút (String)',
      },
      {
        title: 'Quy tắc tác giả',
        namespace: 'ruleBookInfo',
        id: 'author',
        type: 'String',
        hint: 'Chọn tác giả trong nút (String)',
      },
      {
        title: 'Quy tắc phân loại',
        namespace: 'ruleBookInfo',
        id: 'kind',
        type: 'String',
        hint: 'Chọn phân loại trong nút (String)',
      },
      {
        title: 'Quy tắc số chữ',
        namespace: 'ruleBookInfo',
        id: 'wordCount',
        type: 'String',
        hint: 'Chọn số chữ trong nút (String)',
      },
      {
        title: 'Chương mới nhất',
        namespace: 'ruleBookInfo',
        id: 'lastChapter',
        type: 'String',
        hint: 'Chọn chương mới nhất trong nút (String)',
      },
      {
        title: 'Quy tắc giới thiệu',
        namespace: 'ruleBookInfo',
        id: 'intro',
        type: 'String',
        hint: 'Chọn giới thiệu sách trong nút (String)',
      },
      {
        title: 'Quy tắc ảnh bìa',
        namespace: 'ruleBookInfo',
        id: 'coverUrl',
        type: 'String',
        hint: 'Chọn ảnh bìa trong nút (URL String)',
      },
      {
        title: 'Địa chỉ mục lục',
        namespace: 'ruleBookInfo',
        id: 'tocUrl',
        type: 'String',
        hint: 'Chọn URL chi tiết sách (URL String, có thể bỏ nếu trùng trang chi tiết)',
      },
      {
        title: 'Sửa thông tin sách',
        namespace: 'ruleBookInfo',
        id: 'canReName',
        type: 'String',
        hint: 'Cho phép sửa tên sách và tác giả (kết quả String, mặc định không cho phép)',
      },
      {
        title: 'URL tải xuống',
        namespace: 'ruleBookInfo',
        id: 'downloadUrls',
        type: 'String',
        hint: 'Địa chỉ tải của nguồn tệp (kết quả là URL String, nhiều liên kết trả về mảng)',
      },
    ],
  },
  directory: {
    name: 'Mục lục',
    children: [
      {
        title: 'JS trước khi cập nhật',
        namespace: 'ruleToc',
        id: 'preUpdateJs',
        type: 'String',
        hint: 'Chạy JS trước khi cập nhật mục lục để cập nhật liên kết mục lục',
      },
      {
        title: 'Quy tắc danh sách',
        namespace: 'ruleToc',
        id: 'chapterList',
        type: 'String',
        hint: 'Chọn các nút chương trong mục lục (List<Element>)',
      },
      {
        title: 'Tên chương',
        namespace: 'ruleToc',
        id: 'chapterName',
        type: 'String',
        hint: 'Chọn tên chương (String)',
      },
      {
        title: 'Địa chỉ chương',
        namespace: 'ruleToc',
        id: 'chapterUrl',
        type: 'String',
        hint: 'Chọn liên kết chương (URL String)',
      },
      {
        title: 'Xử lý tiêu đề',
        namespace: 'ruleToc',
        id: 'formatJs',
        type: 'String',
        hint: 'Hàm gọi lại cho từng chương sau khi loại trùng. Có các biến index (từ 1), title (tiêu đề), gInt (ban đầu 0); giá trị trả về là tiêu đề mới',
      },
      {
        title: 'Đánh dấu tên quyển',
        namespace: 'ruleToc',
        id: 'isVolume',
        type: 'String',
        hint: 'Tên chương có phải tên quyển (kết quả Bool)',
      },
      {
        title: 'Thông tin chương',
        namespace: 'ruleToc',
        id: 'updateTime',
        type: 'String',
        hint: 'Chọn thông tin chương, như thời gian cập nhật (String)',
      },
      {
        title: 'Đánh dấu trả phí',
        namespace: 'ruleToc',
        id: 'isVip',
        type: 'String',
        hint: 'Chương có phải chương VIP (kết quả Bool)',
      },
      {
        title: 'Đánh dấu đã mua',
        namespace: 'ruleToc',
        id: 'isPay',
        type: 'String',
        hint: 'Chương đã được mua chưa (kết quả Bool)',
      },
      {
        title: 'Quy tắc trang tiếp',
        namespace: 'ruleToc',
        id: 'nextTocUrl',
        type: 'String',
        hint: 'Chọn trang mục lục tiếp theo (List<String> hoặc String)',
      },
    ],
  },
  content: {
    name: 'Nội dung',
    children: [
      {
        title: 'Quy tắc nội dung',
        namespace: 'ruleContent',
        id: 'content',
        type: 'String',
        hint: 'Chọn nội dung chính (String)',
      },
      {
        title: 'Quy tắc nội dung phụ',
        namespace: 'ruleContent',
        id: 'subContent',
        type: 'String',
        hint: 'Chọn nội dung phụ (String)',
      },
      {
        title: 'Quy tắc tiêu đề',
        namespace: 'ruleContent',
        id: 'title',
        type: 'String',
        hint: 'Kết quả sẽ thay thế tiêu đề chương (String)',
      },
      {
        title: 'Quy tắc trang tiếp',
        namespace: 'ruleContent',
        id: 'nextContentUrl',
        type: 'String',
        hint: 'Chọn liên kết trang tiếp theo của chương hiện tại (URL String)',
      },
      {
        title: 'Chèn script',
        namespace: 'ruleContent',
        id: 'webJs',
        type: 'String',
        hint: 'Chèn JavaScript để mô phỏng nhấp chuột… Phải có giá trị trả về, thường là String',
      },
      {
        title: 'Regex tài nguyên',
        namespace: 'ruleContent',
        id: 'sourceRegex',
        type: 'String',
        hint: 'Mẫu URL tài nguyên dùng để dò tìm',
      },
      {
        title: 'Quy tắc thay thế',
        namespace: 'ruleContent',
        id: 'replaceRegex',
        type: 'String',
        hint: 'Thay thế sau khi gộp nhiều trang để làm sạch nội dung',
      },
      {
        title: 'Kiểu ảnh',
        namespace: 'ruleContent',
        id: 'imageStyle',
        type: 'String',
        hint: 'FULL: phủ kín; để trống: kiểu mặc định',
      },
      {
        title: 'Giải mã ảnh',
        namespace: 'ruleContent',
        id: 'imageDecode',
        type: 'String',
        hint: 'Nhập JavaScript trả về bytes của ảnh đã giải mã',
      },
      {
        title: 'Thao tác mua',
        namespace: 'ruleContent',
        id: 'payAction',
        type: 'String',
        hint: 'Nhập JavaScript trả về liên kết mua hoặc gọi API mua',
      },
      {
        title: 'Hàm gọi lại',
        namespace: 'ruleContent',
        id: 'callBackJs',
        type: 'String',
        hint: 'Nhập JavaScript; biến event là tên đối tượng sự kiện',
      },
    ],
  },
  /*
  review: {
    name: "Bình luận đoạn",
    children: [
      {
        title: "URL bình luận đoạn",
        namespace: "ruleReview",
id: "reviewUrl",
        type: "String",
        hint: "URL bình luận đoạn",
      },
      {
        title: "Ảnh đại diện người đăng",
        namespace: "ruleReview",
id: "avatarRule",
        type: "String",
        hint: "Ảnh đại diện người bình luận",
      },
      {
        title: "Nội dung bình luận đoạn",
        namespace: "ruleReview",
id: "contentRule",
        type: "String",
        hint: "Nội dung bình luận đoạn",
      },
      {
        title: "Thời gian đăng",
        namespace: "ruleReview",
id: "postTimeRule",
        type: "String",
        hint: "Thời gian đăng bình luận đoạn",
      },
      {
        title: "URL phản hồi",
        namespace: "ruleReview",
id: "reviewQuoteUrl",
        type: "String",
        hint: "URL lấy phản hồi bình luận đoạn",
      },
      {
        title: "URL thích",
        namespace: "ruleReview",
id: "voteUpUrl",
        type: "String",
        hint: "URL thích",
      },
      {
        title: "URL không thích",
        namespace: "ruleReview",
id: "voteDownUrl",
        type: "String",
        hint: "URL không thích",
      },
      {
        title: "Gửi phản hồi",
        namespace: "ruleReview",
id: "postReviewUrl",
        type: "String",
        hint: "URL gửi phản hồi",
      },
      {
        title: "Phản hồi bình luận đoạn",
        namespace: "ruleReview",
id: "postQuoteUrl",
        type: "String",
        hint: "URL gửi phản hồi bình luận đoạn",
      },
      {
        title: "Xóa bình luận đoạn",
        namespace: "ruleReview",
id: "deleteUrl",
        type: "String",
        hint: "URL xóa bình luận đoạn",
      },
    ],
  },*/
  other: {
    name: 'Khác',
    children: [
      {
        title: 'Bật tìm kiếm',
        id: 'enabled',
        type: 'Boolean',
      },
      {
        title: 'Bật khám phá',
        id: 'enabledExplore',
        type: 'Boolean',
      },
      // {
      //   title: "Bật bình luận đoạn",
      //   id: "enabledReview",
      //   type: "Boolean",
      // },
      {
        title: 'CookieJar',
        id: 'enabledCookieJar',
        type: 'Boolean',
      },
      {
        title: 'Bật lắng nghe sự kiện',
        id: 'eventListener',
        type: 'Boolean',
      },
      {
        title: 'Bật nút tùy chỉnh',
        id: 'customButton',
        type: 'Boolean',
      },
      {
        title: 'Ưu tiên tìm kiếm',
        id: 'weight',
        type: 'Number',
      },
      {
        title: 'Thứ tự sắp xếp',
        id: 'customOrder',
        type: 'Number',
      },
    ],
  },
}
